CREATE TABLE USUARIOS (
	NOMBRE VARCHAR(30),
	APELLIDOS VARCHAR (50),
	CONTRASENIA VARCHAR(20),
	ALIAS VARCHAR(20),
	SECCION VARCHAR(20),
	FECHA DATE,
	EMAIL VARCHAR(50),
	DESCRIPCION VARCHAR(140));


CREATE TABLE BIBLIOTECAS(
	IDBIBLIOTECA INT NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(30),
	AUTOR VARCHAR (80),
	SECCION VARCHAR(20),
	DESCRIPCION VARCHAR(140),
	RUTAIMAGEN VARCHAR(200),
	PRIMARY KEY (IDBIBLIOTECA)
);
/* */


CREATE TABLE SECCIONES(
	IDBIBLIOTECA INT, 
	IDSECCION INT, 
	NOMBRE VARCHAR(20)
);


CREATE TABLE RECURSOS(
	TITULO VARCHAR (30),
	AUTOR VARCHAR(80),
	SECCION VARCHAR(20),
	TIPO VARCHAR(20),
	FECHA DATE, 
	DESCRIPCION VARCHAR(140)
);